/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Processmaker/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PMIO) {
      root.PMIO = {};
    }
    root.PMIO.EventAttributes = factory(root.PMIO.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EventAttributes model module.
   * @module Processmaker/Model/EventAttributes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EventAttributes</code>.
   * @alias module:Processmaker/Model/EventAttributes
   * @class
   * @param name {String} 
   * @param processId {String} 
   * @param type {module:Processmaker/Model/EventAttributes.TypeEnum} 
   * @param definition {module:Processmaker/Model/EventAttributes.DefinitionEnum} 
   */
  var exports = function(name, processId, type, definition) {
    var _this = this;

    _this['name'] = name;

    _this['process_id'] = processId;

    _this['type'] = type;
    _this['definition'] = definition;








  };

  /**
   * Constructs a <code>EventAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Processmaker/Model/EventAttributes} obj Optional instance to populate.
   * @return {module:Processmaker/Model/EventAttributes} The populated <code>EventAttributes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('process_id')) {
        obj['process_id'] = ApiClient.convertToType(data['process_id'], 'String');
      }
      if (data.hasOwnProperty('message_id')) {
        obj['message_id'] = ApiClient.convertToType(data['message_id'], 'Integer');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('definition')) {
        obj['definition'] = ApiClient.convertToType(data['definition'], 'String');
      }
      if (data.hasOwnProperty('interrupting')) {
        obj['interrupting'] = ApiClient.convertToType(data['interrupting'], 'Boolean');
      }
      if (data.hasOwnProperty('condition')) {
        obj['condition'] = ApiClient.convertToType(data['condition'], 'String');
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'String');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
      }
      if (data.hasOwnProperty('cycle')) {
        obj['cycle'] = ApiClient.convertToType(data['cycle'], 'String');
      }
      if (data.hasOwnProperty('attached_to_task_id')) {
        obj['attached_to_task_id'] = ApiClient.convertToType(data['attached_to_task_id'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} process_id
   */
  exports.prototype['process_id'] = undefined;
  /**
   * @member {Integer} message_id
   */
  exports.prototype['message_id'] = undefined;
  /**
   * @member {module:Processmaker/Model/EventAttributes.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:Processmaker/Model/EventAttributes.DefinitionEnum} definition
   */
  exports.prototype['definition'] = undefined;
  /**
   * @member {Boolean} interrupting
   */
  exports.prototype['interrupting'] = undefined;
  /**
   * @member {String} condition
   */
  exports.prototype['condition'] = undefined;
  /**
   * @member {String} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {String} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {String} cycle
   */
  exports.prototype['cycle'] = undefined;
  /**
   * @member {String} attached_to_task_id
   */
  exports.prototype['attached_to_task_id'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "START"
     * @const
     */
    "START": "START",
    /**
     * value: "END"
     * @const
     */
    "END": "END",
    /**
     * value: "INTERMEDIATE_CATCH"
     * @const
     */
    "INTERMEDIATE_CATCH": "INTERMEDIATE_CATCH",
    /**
     * value: "INTERMEDIATE_THROW"
     * @const
     */
    "INTERMEDIATE_THROW": "INTERMEDIATE_THROW",
    /**
     * value: "BOUNDARY"
     * @const
     */
    "BOUNDARY": "BOUNDARY",
    /**
     * value: "IMPLICIT_THROW"
     * @const
     */
    "IMPLICIT_THROW": "IMPLICIT_THROW"  };

  /**
   * Allowed values for the <code>definition</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DefinitionEnum = {
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE",
    /**
     * value: "CANCEL"
     * @const
     */
    "CANCEL": "CANCEL",
    /**
     * value: "COMPENSATION"
     * @const
     */
    "COMPENSATION": "COMPENSATION",
    /**
     * value: "ERROR"
     * @const
     */
    "ERROR": "ERROR",
    /**
     * value: "ESCALATION"
     * @const
     */
    "ESCALATION": "ESCALATION",
    /**
     * value: "MESSAGE"
     * @const
     */
    "MESSAGE": "MESSAGE",
    /**
     * value: "LINK"
     * @const
     */
    "LINK": "LINK",
    /**
     * value: "SIGNAL"
     * @const
     */
    "SIGNAL": "SIGNAL",
    /**
     * value: "TERMINATE"
     * @const
     */
    "TERMINATE": "TERMINATE",
    /**
     * value: "TIMER"
     * @const
     */
    "TIMER": "TIMER"  };


  return exports;
}));


