/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Processmaker/ApiClient', 'Processmaker/Model/AggregatedLog'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AggregatedLog'));
  } else {
    // Browser globals (root is window)
    if (!root.PMIO) {
      root.PMIO = {};
    }
    root.PMIO.ListAggregatedLogCollection = factory(root.PMIO.ApiClient, root.PMIO.AggregatedLog);
  }
}(this, function(ApiClient, AggregatedLog) {
  'use strict';




  /**
   * The ListAggregatedLogCollection model module.
   * @module Processmaker/Model/ListAggregatedLogCollection
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ListAggregatedLogCollection</code>.
   * JSON API response with a collection of the Logs in an array
   * @alias module:Processmaker/Model/ListAggregatedLogCollection
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>ListAggregatedLogCollection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Processmaker/Model/ListAggregatedLogCollection} obj Optional instance to populate.
   * @return {module:Processmaker/Model/ListAggregatedLogCollection} The populated <code>ListAggregatedLogCollection</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [AggregatedLog]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:Processmaker/Model/AggregatedLog>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


