/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['Processmaker/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PMIO) {
      root.PMIO = {};
    }
    root.PMIO.TokenAttributes = factory(root.PMIO.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TokenAttributes model module.
   * @module Processmaker/Model/TokenAttributes
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TokenAttributes</code>.
   * @alias module:Processmaker/Model/TokenAttributes
   * @class
   * @param instanceId {String} 
   */
  var exports = function(instanceId) {
    var _this = this;

    _this['instance_id'] = instanceId;









  };

  /**
   * Constructs a <code>TokenAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Processmaker/Model/TokenAttributes} obj Optional instance to populate.
   * @return {module:Processmaker/Model/TokenAttributes} The populated <code>TokenAttributes</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('instance_id')) {
        obj['instance_id'] = ApiClient.convertToType(data['instance_id'], 'String');
      }
      if (data.hasOwnProperty('flow_id')) {
        obj['flow_id'] = ApiClient.convertToType(data['flow_id'], 'String');
      }
      if (data.hasOwnProperty('token_key')) {
        obj['token_key'] = ApiClient.convertToType(data['token_key'], 'String');
      }
      if (data.hasOwnProperty('token_count')) {
        obj['token_count'] = ApiClient.convertToType(data['token_count'], 'Integer');
      }
      if (data.hasOwnProperty('initiator_object_id')) {
        obj['initiator_object_id'] = ApiClient.convertToType(data['initiator_object_id'], 'String');
      }
      if (data.hasOwnProperty('initiator_object_type')) {
        obj['initiator_object_type'] = ApiClient.convertToType(data['initiator_object_type'], 'String');
      }
      if (data.hasOwnProperty('target_object_id')) {
        obj['target_object_id'] = ApiClient.convertToType(data['target_object_id'], 'String');
      }
      if (data.hasOwnProperty('target_object_type')) {
        obj['target_object_type'] = ApiClient.convertToType(data['target_object_type'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} instance_id
   */
  exports.prototype['instance_id'] = undefined;
  /**
   * @member {String} flow_id
   */
  exports.prototype['flow_id'] = undefined;
  /**
   * @member {String} token_key
   */
  exports.prototype['token_key'] = undefined;
  /**
   * @member {Integer} token_count
   */
  exports.prototype['token_count'] = undefined;
  /**
   * @member {String} initiator_object_id
   */
  exports.prototype['initiator_object_id'] = undefined;
  /**
   * @member {String} initiator_object_type
   */
  exports.prototype['initiator_object_type'] = undefined;
  /**
   * @member {String} target_object_id
   */
  exports.prototype['target_object_id'] = undefined;
  /**
   * @member {String} target_object_type
   */
  exports.prototype['target_object_type'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


