/**
 * ProcessMaker API
 * This ProcessMaker I/O API provides access to a BPMN 2.0 compliant workflow engine API that is designed to be used as a microservice to support enterprise cloud applications. The current Alpha 1.0 version supports most of the descriptive classes of the BPMN 2.0 specification.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@processmaker.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PMIO);
  }
}(this, function(expect, PMIO) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PMIO.Event();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Event', function() {
    describe('addEvent', function() {
      it('should call addEvent successfully', function(done) {
        //uncomment below and update the code to test addEvent
        //instance.addEvent(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addEventConnector', function() {
      it('should call addEventConnector successfully', function(done) {
        //uncomment below and update the code to test addEventConnector
        //instance.addEventConnector(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEvent', function() {
      it('should call deleteEvent successfully', function(done) {
        //uncomment below and update the code to test deleteEvent
        //instance.deleteEvent(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEventConnector', function() {
      it('should call deleteEventConnector successfully', function(done) {
        //uncomment below and update the code to test deleteEventConnector
        //instance.deleteEventConnector(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventTrigger', function() {
      it('should call eventTrigger successfully', function(done) {
        //uncomment below and update the code to test eventTrigger
        //instance.eventTrigger(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eventWebhook', function() {
      it('should call eventWebhook successfully', function(done) {
        //uncomment below and update the code to test eventWebhook
        //instance.eventWebhook(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findEventById', function() {
      it('should call findEventById successfully', function(done) {
        //uncomment below and update the code to test findEventById
        //instance.findEventById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findEventConnectorById', function() {
      it('should call findEventConnectorById successfully', function(done) {
        //uncomment below and update the code to test findEventConnectorById
        //instance.findEventConnectorById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findEventConnectors', function() {
      it('should call findEventConnectors successfully', function(done) {
        //uncomment below and update the code to test findEventConnectors
        //instance.findEventConnectors(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findEvents', function() {
      it('should call findEvents successfully', function(done) {
        //uncomment below and update the code to test findEvents
        //instance.findEvents(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEvent', function() {
      it('should call updateEvent successfully', function(done) {
        //uncomment below and update the code to test updateEvent
        //instance.updateEvent(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEventConnector', function() {
      it('should call updateEventConnector successfully', function(done) {
        //uncomment below and update the code to test updateEventConnector
        //instance.updateEventConnector(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
